apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-interest-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-interest-calculator
  template:
    metadata:
      labels:
        app: simple-interest-calculator
    spec:
      containers:
      - name: simple-interest-calculator
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: simple-interest-calculator-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-interest-calculator-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width">
      <title>Simple Interest Calculator</title>
      <link href="style.css" rel="stylesheet" type="text/css" />
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Courgette&family=Salsa&display=swap" rel="stylesheet">
    </head>
    <body>
      <h1>SIMPLE INTEREST <br>CALCULATOR</h1>
      <div class="values" id="value">
        <div class="row">
            <div class="principal common">
              <label for="principal">Principal($) : </label>
              <input type="number" id="principal" class="trans-input">
            </div>
            <div class="rate common">
              <label for="rate">Rate : </label>
              <input type="number" id="rate"  class="trans-input">
            </div>
        </div>
        <div class="time common">
          <label for="time">Time : </label>
          <input type="number" id="time"  class="trans-input">
          <select id="selector">
            <option value="Year">Year</option>
            <option value="Month">Month</option>
          </select>
        </div>
        <div class="calc" onclick="calculator()">
          <input type="button" value="Calculate" id="calculate">
        </div>
        <div class="result" id="result">
            <h4>Principal: $0.00<br></h4>
            <h4>Interest: $0.00<br></h4>
            <h4>Amount: $0.00</h4>
        </div>
      </div>
      <div id="errormsg"></div>
      <script src="script.js"></script>
    </body>
    </html>
  style.css: |
    body {
      font-family: 'Salsa', cursive;
      background-color: white;
      height: 100vh;
      font-size: 1.3em;
    }
    * {
    padding: 0;
    margin: 0;
    box-sizing: border-box;
    }
  
    input {
    font-size: 0.9em;
    width: 90%;
    font-weight: bold;
    }
  
    h1 {
      text-align: center;
    }
    
    .values {
      background-color: grey;
      padding: 2rem;
      margin: 1rem;
      box-shadow: 5px 5px 5px black;
      border-radius: 10px;
      /* height:90%; */
    
    }
    
    .trans-input {
      background-color: transparent;
      border: none;
      outline: none;
      margin-top: 10px;
      border-bottom: 2px solid white;
    }
    
    .trans-input:focus {
      border-bottom: 2px solid black;
    }
    
    select {
      /* padding:5px; */
      font-size: 1em;
      color: white;
      /* border: 2px solid #41AEA9; */
      border-radius: 10px;
      background-color: black;
      outline: none;
      margin-top: 1rem;
      padding: 0.5rem;
    }
    
    select:focus {
      border: 2px solid black;
    }
    
    option {
      /* background-color:aqua; */
      border-radius: 10px;
    }
    
    #calculate {
      font-family: 'Courgette', cursive;
      /* font-family: 'Salsa', cursive; */
      font-size: 1.4em;
      padding: 0.5rem;
      /* text-align: center; */
      margin: 1rem;
      border-radius: 5px;
      background-color: #24d292;
    }
    
    #calculate:hover {
      background-color: #34e3a2;
    }
    
    .common {
      margin-top: 0.8rem;
    }
    
    .result {
      margin-bottom: 1rem;
    }
    
    h4 {
      font-weight: lighter;
    }
    
    @media screen and (min-width: 1024px) {
      body {
        font-size: 30px;
        height: 100vh;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
      }
    
      .values {
        width: 40%;
      }
    
      input {
        width: 46%;
      }
    
      .row {
        display: flex;
      }
    
      select {
        margin-left: 2rem;
      }
    
      #calculate {
        margin-left: 10rem;
      }
    }
    
    @media screen and (min-width: 768px) and (max-width: 1024px) {
      body {
        font-size: 2em;
      }
    
      input {
        width: 60%;
      }
    
      select {
        margin-left: 1rem;
        font-size: 1em;
      }
    
      option {
        font-size: 0.7em;
      }
    
      #calculate {
        margin-left: 7rem;
        margin-top: 2rem;
      }
    }
  script.js: |
    let calculateButton = document.getElementById("calculate");
    let result = document.getElementById("result");
    let principal = document.getElementById("principal");
    let rate = document.getElementById("rate");
    let time = document.getElementById("time");
    let duration = document.getElementById("selector");
    let error = document.getElementById("errormsg");
    
    function calculator() {
      let p = parseFloat(principal.value);
      let r = parseFloat(rate.value);
      let t = parseFloat(time.value);
      let d = duration.value;
      let calculatedInterest;
      if(!p || !r || !t){
        error.textContent = "Please Enter the Input";
        error.style.color = "red";
      } else {
        error.textContent = " ";
        if (isNaN(p) || isNaN(r) || isNaN(t)) {
          showResult(0, 0, 0);
          return;
        }
        if (d === "Year") {
          calculatedInterest = (p * r * t) / 100;
        } else {
          calculatedInterest = (p * r * t) / 1200;
        }
        let calculatedAmount = p + calculatedInterest;
        showResult(p, calculatedInterest, calculatedAmount);
      }
    }
    function showResult(principal, output, amount) {
      result.innerHTML = "Principal:  $" + principal.toFixed(2) + "<br>Interest:  $" + output.toFixed(2) + "<br>Amount:  $" + amount.toFixed(2);
    }
