apiVersion: v1
kind: Service
metadata:
  name: simple-interest-calculator-service
spec:
  selector:
    app: simple-interest-calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
